### ISSUE TITLE
How to require/import the module

### ISSUE THREAD

**Issue by joanasleet** [amercier/ng-media-events#2]
I can't import the module into my code using

`require('ng-media-events')`
`import 'ng-media-events'`

although the folder with the name **ng-media-events** exists in node_modules.
 
The error is _Module not found: Can't resolve 'ng-media-events' in ..._

**Comment by amercier** [comment]
Fixed in version 1.0.3 (added `main` entry in `package.json`). You should now be able to import it using CJS-style `import`/`require`.

**Comment by joanasleet** [comment]
Works nice. Thanks for the quick help!
